apiVersion: v1
kind: Pod
metadata:
  name: myconfigfile
spec:
  containers:
    - name: c1
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo hello krushna; sleep 5; done"]
      volumeMounts:
        - name: testconfigmap
          mountPath: "/tmp/config"
  volumes:
    - name: testconfigmap
      configMap:
        name: mymap
        items:
          - key: sample.conf
            path: sample.conf

