apiVersion: v1
kind: persistentVolume
metadata:
  name: myvolume
spec:
  capacity:
    storage: 1GB
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPloicy: Recycle
  awsElasticBlockStore:
    volumeID: #give here your Volume id from aws
    fsType: ext4
